{
 "title": "Fluxum - Backend (Node.js)",
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU (s) total",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "process_cpu_seconds_total" }
   ]
  },
  {
   "title": "Memória (RSS)",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  },
  {
   "title": "Event Loop Lag (p99)",
   "type": "gauge",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_p99_seconds"
    }
   ]
  },
  {
   "title": "Requests por segundo (RPS)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 7 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Latência - p50/p90/p99",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 4, "w": 12, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,  sum by (le) (rate(http_request_duration_seconds_bucket[1m])))"
    },
    {
     "expr": "histogram_quantile(0.9,  sum by (le) (rate(http_request_duration_seconds_bucket[1m])))"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket[1m])))"
    }
   ]
  },
  {
   "title": "Requests por rota (1m)",
   "type": "bargauge",
   "gridPos": { "x": 0, "y": 11, "w": 12, "h": 7 },
   "targets": [
    {
     "expr": "topk(10, sum by (method, route) (rate(http_request_duration_seconds_count[1m])))"
    }
   ]
  },
  {
   "title": "GC Duration (sum por tipo)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 11, "w": 12, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (kind) (rate(nodejs_gc_duration_seconds_sum[1m]))"
    }
   ]
  },
  {
   "title": "Handles ativos",
   "type": "stat",
   "gridPos": { "x": 0, "y": 18, "w": 6, "h": 4 },
   "targets": [
    { "expr": "nodejs_active_handles_total" }
   ]
  },
  {
   "title": "Resources ativos",
   "type": "stat",
   "gridPos": { "x": 6, "y": 18, "w": 6, "h": 4 },
   "targets": [
    { "expr": "nodejs_active_resources_total" }
   ]
  },
  {
   "title": "Uptime (início do processo)",
   "type": "stat",
   "gridPos": { "x": 12, "y": 18, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "process_start_time_seconds" }
   ]
  }
 ]
}